api_keys:  # A mapping of unique api keys (x-api-key header) to workspaces (listed below)
  null: public
  public: public
workspaces:  # Unique workspaces
  public:  # A machine-readable name
    name: Public  # A human-readable name
    domains:  # List of domains this workspace users can use
      - general
domains:  # Domains of translation engines
  general:  # A machine-readable domain name. The "domain" value used in requests.
    name: "General"  # A human-readable domain name. Displayed in CAT tool configuration menus.
    languages: [
      # A list of language pairs available in this domain. Should be hyphen-separated and use 3-letter codes.
      # German should be 'ger' not 'deu'. Used by CAT tools to determine available languages.
      "eng-eng", "est-eng", "ger-eng", "lit-eng", "lav-eng", "fin-eng", "rus-eng",
      "eng-est", "est-eng", "ger-est", "lit-est", "lav-est", "fin-est", "rus-est",
      "eng-ger", "est-ger", "ger-ger", "lit-ger", "lav-ger", "fin-ger", "rus-ger",
      "eng-lit", "est-lit", "ger-lit", "lit-lit", "lav-lit", "fin-lit", "rus-lit",
      "eng-lav", "est-lav", "ger-lav", "lit-lav", "lav-lav", "fin-lav", "rus-lav",
      "eng-rus", "est-rus", "ger-rus", "lit-rus", "lav-rus", "fin-fin", "fin-rus",
      "eng-fin", "est-fin", "ger-fin", "lit-fin", "lav-fin", "rus-fin", "rus-rus"
    ]
language_codes:  # A mapping of all language code formats to the default 3-letter format
    { "et": "est", "est": "est", "en": "eng", "eng": "eng", "de": "ger", "deu": "ger", "ger": "ger", "lt": "lit",
      "lit": "lit", "fi": "fin", "fin": "fin", "lv": "lav", "lav": "lav", "ru": "rus", "rus": "rus" }
corrections_data_storage_path: "storage/corrections.txt" # A path to the file with user-corrected translations data